apiVersion: mixapp.easystack.io/v1
kind: VirtualMachine
metadata:
  name: test-ap
  namespace: application
spec:
  auth:
    projectID: "debb3a36af9c40a1a7438463951802cd"
    token: ""
  server:
    replicas: 2
    name: "test-app"
    boot_image: "test"
    flavor: 1C-1G
    availability_zone: "default-az"
    admin_pass: "passw0rd"
    boot_volume:
      volume_delete: true
      volume_type: "hdd"
      volume_size: 4
    volumes:
    - volume_delete: true
      volume_type: "hdd"
      volume_size: 2
    user_data: "echo test"
    security_group:
    - "default"
    subnet:
      subnet_id: "eks-test"
  loadbalance:
    subnet:
      subnet_id: "eks-test"
    loadbalance_ip: "10.0.15.2"
    name: "net"
    port_map:
      - port: 443
        protocol: "TCP"
  assemblyPhase: "Creating"
