apiVersion: mixapp.easystack.io/v1
kind: VirtualMachine
metadata:
  name: test-app-8e5eda4cac9f460ea2b471a357c42dd0
spec:
  # Add fields here
  project:
    projectID: "8e5eda4cac9f460ea2b471a357c42dd0"
    token: "gAAAAABes7ueQgb_EpiD7hhg7miC7uibqzt-Ce3Ly4ztQXJXwVZ-q5NdSdMSAhsJTxzd6flYTIeddJYLuxh7MsVs_qbpS7Ds8v27erZRRY8PQqe8xmwHlyCLOCfcv6FGHG7M-zIxIvM58NOKIGx_peC1kUl3UGb1x9QWbnn1HjzMQldpdN1tVvE"
  server:
    replicas: 1
    name_prefix: "test-app"
    image: "11c9463b-43dd-4701-8942-3ea1ba22ff3f"
    flavor: "1-512-20"
    availability_zone: "nova"
    admin_pass: "passw0rd"
    boot_volume_type: "hdd"
    boot_volume_size: "20G"
    security_group: "default"
  network:
    external_network: "public_net"
    private_network_cidr: "192.168.18.0/24"
    private_network_name: "ecns-private"
  assemblyPhase: "Creating"
