apiVersion: mixapp.easystack.io/v1
kind: VirtualMachine
metadata:
  name: test-ap1

spec:
  auth:
    projectID: "e89beec2eecd4bfaa080054b54bd101f"
    token: "gAAAAABfTMmhNet2hOYkRS0X9eITxHdDGqdSu-gMIr23afulmvjbQEi3_znCS25iWSsCQa-2DAMjYoWzXFRjlcJD_Qsrj5f3kMezKWbGKDPDIrOoPuPNhfm5tQ6OJkKPyG2SpmYlEMhMQ1zRFC1JDcOR24gdryyhHYqhp6nyiuXcyhVt2BipADqgoo3H8xsFAQPvlOM9mtip"
  server:
    admin_pass: "12"
    availability_zone: default-az
    boot_image: TestVM
    boot_volume:
      volume_delete: false
      volume_size: 1
      volume_type: hdd
    flavor: 1C-1G
    name: bisdfkl11
    replicas: 1
    security_groups:
      - default
    subnet:
      network_id: 66b682b6-43f4-4683-be1d-87b940f30251
      network_name: network_4MiwkC
      subnet_id: 9de2235c-050b-4741-9f52-7b9f4604efb5
      subnet_name: network_4MiwkC_default_ipv4_subnet2

  assemblyPhase: "Creating"
